const alunos = [
  {
    aluno: 'Paulo',
    turma: '',
    curso: '',
    materias: {
      matéria1: '',
      nota1: 0,
      nota2: 0,
      nota3: 0,
      nota4: 0,
      media: (this.nota1 + this.nota2 + this.nota3 + this.nota4) / 4,
      professor: '',
      matéria2: '',
      nota1: 0,
      nota2: 0,
      nota3: 0,
      nota4: 0,
      media: (this.nota1 + this.nota2 + this.nota3 + this.nota4) / 4,
      professor: '',
      matéria3: '',
      nota1: 0,
      nota2: 0,
      nota3: 0,
      nota4: 0,
      media: (this.nota1 + this.nota2 + this.nota3 + this.nota4) / 4,
      professor: '',
      matéria4: '',
      nota1: 0,
      nota2: 0,
      nota3: 0,
      nota4: 0,
      media: (this.nota1 + this.nota2 + this.nota3 + this.nota4) / 4,
      professor: '',
      matéria5: '',
      nota1: 0,
      nota2: 0,
      nota3: 0,
      nota4: 0,
      media: (this.nota1 + this.nota2 + this.nota3 + this.nota4) / 4,
      professor: '',
    },
    status: '',
  },
  {
    aluno: 'Ellen',
    turma: '',
    curso: '',
    materias: {
      matéria1: '',
      nota1: 0,
      nota2: 0,
      nota3: 0,
      nota4: 0,
      media: (this.nota1 + this.nota2 + this.nota3 + this.nota4) / 4,
      professor: '',
      matéria2: '',
      nota1: 0,
      nota2: 0,
      nota3: 0,
      nota4: 0,
      media: (this.nota1 + this.nota2 + this.nota3 + this.nota4) / 4,
      professor: '',
      matéria3: '',
      nota1: 0,
      nota2: 0,
      nota3: 0,
      nota4: 0,
      media: (this.nota1 + this.nota2 + this.nota3 + this.nota4) / 4,
      professor: '',
      matéria4: '',
      nota1: 0,
      nota2: 0,
      nota3: 0,
      nota4: 0,
      media: (this.nota1 + this.nota2 + this.nota3 + this.nota4) / 4,
      professor: '',
      matéria5: '',
      nota1: 0,
      nota2: 0,
      nota3: 0,
      nota4: 0,
      media: (this.nota1 + this.nota2 + this.nota3 + this.nota4) / 4,
      professor: '',
    },
    status: '',
  },
  {
    aluno: 'Gabriel',
    turma: '',
    curso: '',
    materias: {
      matéria1: '',
      nota1: 0,
      nota2: 0,
      nota3: 0,
      nota4: 0,
      media: (this.nota1 + this.nota2 + this.nota3 + this.nota4) / 4,
      professor: '',
      matéria2: '',
      nota1: 0,
      nota2: 0,
      nota3: 0,
      nota4: 0,
      media: (this.nota1 + this.nota2 + this.nota3 + this.nota4) / 4,
      professor: '',
      matéria3: '',
      nota1: 0,
      nota2: 0,
      nota3: 0,
      nota4: 0,
      media: (this.nota1 + this.nota2 + this.nota3 + this.nota4) / 4,
      professor: '',
      matéria4: '',
      nota1: 0,
      nota2: 0,
      nota3: 0,
      nota4: 0,
      media: (this.nota1 + this.nota2 + this.nota3 + this.nota4) / 4,
      professor: '',
      matéria5: '',
      nota1: 0,
      nota2: 0,
      nota3: 0,
      nota4: 0,
      media: (this.nota1 + this.nota2 + this.nota3 + this.nota4) / 4,
      professor: '',
    },
    status: '',
  },
  {
    aluno: 'Samuel',
    turma: '',
    curso: '',
    materias: {
      matéria1: '',
      nota1: 0,
      nota2: 0,
      nota3: 0,
      nota4: 0,
      media: (this.nota1 + this.nota2 + this.nota3 + this.nota4) / 4,
      professor: '',
      matéria2: '',
      nota1: 0,
      nota2: 0,
      nota3: 0,
      nota4: 0,
      media: (this.nota1 + this.nota2 + this.nota3 + this.nota4) / 4,
      professor: '',
      matéria3: '',
      nota1: 0,
      nota2: 0,
      nota3: 0,
      nota4: 0,
      media: (this.nota1 + this.nota2 + this.nota3 + this.nota4) / 4,
      professor: '',
      matéria4: '',
      nota1: 0,
      nota2: 0,
      nota3: 0,
      nota4: 0,
      media: (this.nota1 + this.nota2 + this.nota3 + this.nota4) / 4,
      professor: '',
      matéria5: '',
      nota1: 0,
      nota2: 0,
      nota3: 0,
      nota4: 0,
      media: (this.nota1 + this.nota2 + this.nota3 + this.nota4) / 4,
      professor: '',
    },
    status: '',
  },
];

module.exports = alunos;
